target_sources(SandboxGeometry
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/SandboxGeometryStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Aabb2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Aabb2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Circle2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Circle2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Line2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Line2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Obb2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Obb2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Plane2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Plane2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Ray2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Shapes2d/Ray2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/RayIntersectionPoint2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/RayIntersectionPoint2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/RayResult2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/RayResult2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/IntersectionResult2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/IntersectionResult2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/RayTests2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/RayTests2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/ManifoldPoint2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/ManifoldPoint2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/Manifold2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Intersection2d/Manifold2d.hpp
)
