################################################################################
# Generated using Joshua T. Fisher's 'CMake Builder'.
# Link: https://github.com/playmer/CmakeBuilder 
################################################################################
target_sources(Physics2dCore
  PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Precompiled.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Physics2dCoreStandard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Physics2dCoreLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Physics2dCoreLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/Collider2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/Collider2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/BoxCollider2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/BoxCollider2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/CircleCollider2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/Colliders/CircleCollider2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/RigidBody2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Components/RigidBody2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/CollisionLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/CollisionLibrary.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/ContactManifold2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/ContactManifold2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Collider2dRaycastResult.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Collider2dRaycastResult.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/BroadphaseLayerType.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/IBroadphase2dManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/IBroadphase2dManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/SimpleBroadphase2dManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/SimpleBroadphase2dManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/StaticDynamicBroadphase2dManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/StaticDynamicBroadphase2dManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/FullBroadphase2dManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Detection/Broadphase/FullBroadphase2dManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Events/Events.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Events/Events.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Events/ComponentCreatedEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Events/ComponentCreatedEvent.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Events/PropertyChangedEvent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Events/PropertyChangedEvent.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Queries/Collider2dCastResult.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Queries/Collider2dCastResult.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Queries/Collider2dCastResults.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Queries/Collider2dCastResults.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Queries/SortedResults.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Resources/Physics2dMaterial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Resources/Physics2dMaterial.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Resources/Physics2dMaterialManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Resources/Physics2dMaterialManager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/Collider2dPair.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/Collider2dShapes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/Collider2dShapes.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/Integration2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/Integration2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/MassProperties2d.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/MassComputation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/MassComputation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/TransformComputation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Utilities/TransformComputation.hpp
)
